# swagger: '2.0'
info:
  description: >-
    Public financial disclosure data from OGE form 278e. Entries should be read
    with the employee's separate ethics agreement and the endnotes included in
    the final table, which often indicate whether the employee intends to divest
    the asset upon entering government.
  version: 0.1.0
  title: PFD Filing
paths: {}
definitions:
  filer-s-positions-held-outside-united-states-government:
    title: 1. Filer's Positions Held Outside United States Government
    aliases:
      - 1. Filer Positions Held outside United States Government
      - 1. Filer's Positions Held Outside the United States Government
    description: >-
      Part 1 discloses positions that the filer held at any time during the
      reporting period (excluding positions with the United States Government).
      Positions are reportable even if the filer did not receive compensation.
      This section does not include the following: (1) positions with religious,
      social, fraternal, or political organizations; (2) positions solely of an
      honorary nature; (3) positions held as part of the filer's official duties
      with the United States Government; (4) mere membership in an organization;
      and (5) passive investment interests as a limited partner or non-managing
      member of a limited liability company.
    type: object
    properties:
#      file:
#        type: string
      '#':
        type: string
      organization-name:
        type: string
        aliases:
          - name
      city-state:
        type: string
      organization-type:
        type: string
        aliases:
          - oge-type
          - org-type
      position-held:
        type: string
        aliases:
          - position
      from:
        type: string
      to:
        type: string
  filer-s-employment-assets-&-income-and-retirement-accounts:
    title: 2. Filer's Employment Assets & Income and Retirement Accounts
    aliases:
      - 2. Filer's Employment Assets and Income
    description: >-
      Part 2 discloses the following: Sources of earned and other non-investment
      income of the filer totaling more than $200 during the reporting period
      (e.g., salary, fees, partnership share, honoraria, scholarships, and
      prizes); Assets related to the filer's business, employment, or other
      income-generating activities that (1) ended the reporting period with a
      value greater than $1,000 or (2) produced more than $200 in income during
      the reporting period (e.g., equity in business or partnership, stock
      options, retirement plans/accounts and their underlying holdings as
      appropriate, deferred compensation, and intellectual property, such as
      book deals and patents). This section does not include assets or income
      from United States Government employment or assets that were acquired
      separately from the filer's business, employment, or other
      income-generating activities (e.g., assets purchased through a brokerage
      account). Note: The type of income is not required if the amount of income
      is $0 - $200 or if the asset qualifies as an excepted investment fund
      (EIF).
    type: object
    properties:
#      file:
#        type: string
      '#':
        type: string
      description:
        type: string
      eif:
        type: string
      value:
        type: string
      income-type:
        type: string
      income-amount:
        type: string
  filer-s-employment-agreements-and-arrangements:
    title: 3. Filer's Employment Agreements and Arrangements
    aliases:
      - 3. Filer Employment Agreements and Arrangements
    description: >-
      Part 3 discloses agreements or arrangements that the filer had during the
      reporting period with an employer or former employer (except the United
      States Government), such as the following: Future employment; Leave of
      absence; Continuing payments from an employer, including severance and
      payments not yet received for previous work (excluding ordinary salary
      from a current employer); Continuing participation in an employee welfare,
      retirement, or other benefit plan, such as pensions or a deferred
      compensation plan; Retention or disposition of employer-awarded equity,
      sharing in profits or carried interests (e.g., vested and unvested stock
      options, restricted stock, future share of a company's profits, etc.).
    type: object
    properties:
#      file:
#        type: string
      '#':
        type: string
      employer-or-party:
        type: string
        aliases:
          - employer-other-party-to-agreement-arrangement
      city-state:
        type: string
      status-and-terms:
        type: string
      date:
        type: string
  filer-s-sources-of-compensation-exceeding-$5-000-in-a-year:
    title: '4. Filer''s Sources of Compensation Exceeding $5,000 in a Year'
    description: >-
      Part 4 discloses sources (except the United States Government) that paid
      more than $5,000 in a calendar year for the filer's services during any
      year of the reporting period. The filer discloses payments both from
      employers and from any clients to whom the filer personally provided
      services. The filer discloses a source even if the source made its payment
      to the filer's employer and not to the filer. The filer does not disclose
      a client's payment to the filer's employer if the filer did not provide
      the services for which the client is paying.
    type: object
    properties:
#      file:
#        type: string
      '#':
        type: string
      source-name:
        type: string
        aliases:
          - name
      city-state:
        type: string
      brief-description-of-duties:
        type: string
        aliases:
          - description
  spouse-s-employment-assets-&-income-and-retirement-accounts:
    title: 5. Spouse's Employment Assets & Income and Retirement accounts
    aliases:
      - 5. Spouse's Employment Assets and Income
    description: >-
      Part 5 discloses the following: Sources of earned income (excluding
      honoraria) for the filer's spouse totaling more than $1,000 during the
      reporting period (e.g., salary, consulting fees, and partnership share);
      Sources of honoraria for the filer's spouse greater than $200 during the
      reporting period; Assets related to the filer's spouse's employment,
      business activities, other income-generating activities that (1) ended the
      reporting period with a value greater than $1,000 or (2) produced more
      than $200 in income during the reporting period (e.g., equity in business
      or partnership, stock options, retirement plans/accounts; and their
      underlying holdings as appropriate, deferred compensation, and
      intellectual property, such as book deals and patents); This section does
      not include assets or income from United States Government employment or
      assets that were acquired separately from the filer's spouse's business,
      employment, or other income-generating activities (e.g., assets purchased
      through a brokerage account). Note: The type of income is not required if
      the amount of income is $0 - $200 or if the asset qualifies as an excepted
      investment fund (EIF). Amounts of income are not required for a spouse's
      earned income (excluding honoraria).
    type: object
    properties:
#      file:
#        type: string
      '#':
        type: string
      description:
        type: string
      eif:
        type: string
      value:
        type: string
      income-type:
        type: string
      income-amount:
        type: string
  other-assets-and-income:
    title: 6. Other Assets and Income
    description: >-
      Part 6 discloses each asset, not already reported, that (1) ended the
      reporting period with a value greater than $1,000 or (2) produced more
      than $200 in investment income during the reporting period. For purposes
      of the value and income thresholds, the filer aggregates the filer's
      interests with those of the filer's spouse and dependent children. This
      section does not include the following types of assets: (1) a personal
      residence (unless it was rented out during the reporting period); (2)
      income or retirement benefits associated with United States Government
      employment (e.g., Thrift Savings Plan); and (3) cash accounts (e.g.,
      checking, savings, money market accounts) at a single financial
      institution with a value of $5,000 or less (unless more than $200 of
      income was produced). Additional exceptions apply. Note: The type of
      income is not required if the amount of income is $0 - $200 or if the
      asset qualifies as an excepted investment fund (EIF).
    type: object
    properties:
#      file:
#        type: string
      '#':
        type: string
      description:
        type: string
      eif:
        type: string
      value:
        type: string
      income-type:
        type: string
      income-amount:
        type: string
  transactions:
    title: 7. Transactions
    description: >-
      Part 7 discloses purchases, sales, or exchanges of real property or
      securities in excess of $1,000 made on behalf of the filer, the filer's
      spouse or dependent child during reporting period. This section does not
      include transactions that concern the following: (1) a personal residence,
      unless rented out; (2) cash accounts (e.g., checking, savings, CDs, money
      market accounts) and money market mutual funds; (3) Treasury bills, bonds,
      and notes; and (4) holdings within a federal Thrift Savings Plan account.
      Additional exceptions apply.
    type: object
    properties:
#      file:
#        type: string
      '#':
        type: string
      description:
        type: string
      type:
        type: string
      date:
        type: string
      amount:
        type: string
  liabilities:
    title: 8. Liabilities
    description: >-
      Part 8 discloses liabilities over $10,000 that the filer, the filer's
      spouse or dependent child owed at any time during the reporting period.
      This section does not include the following types of liabilities: (1)
      mortgages on a personal residence, unless rented out (limitations apply
      for PAS filers); (2) loans secured by a personal motor vehicle, household
      furniture, or appliances, unless the loan exceeds the item's purchase
      price; and (3) revolving charge accounts, such as credit card balances, if
      the outstanding liability did not exceed $10,000 at the end of the
      reporting period. Additional exceptions apply.
    type: object
    properties:
#      file:
#        type: string
      '#':
        type: string
      creditor-name:
        type: string
      type:
        type: string
        aliases:
          - type-of-liability
      amount:
        type: string
      year-incurred:
        type: string
      rate:
        type: string
        aliases:
          - interest-rate
      term:
        type: string
  gifts-and-travel-reimbursements:
    title: 9. Gifts and Travel Reimbursements
    aliases:
      - 9. Gifts and Reimbursements
    description: >-
      This section discloses: Gifts totaling more than $375 that the filer, the
      filer's spouse, and dependent children received from any one source during
      the reporting period; Travel reimbursements totaling more than $375 that
      the filer, the filer's spouse, and dependent children received from any
      one source during the reporting period. For purposes of this section, the
      filer need not aggregate any gift or travel reimbursement with a value of
      $150 or less. Regardless of the value, this section does not include the
      following items: (1) anything received from relatives; (2) anything
      received from the United States Government or from the District of
      Columbia, state, or local governments; (3) bequests and other forms of
      inheritance; (4) gifts and travel reimbursements given to the filer's
      agency in connection with the filer's official travel; (5) gifts of
      hospitality (food, lodging, entertainment) at the donor's residence or
      personal premises; and (6) anything received by the filer's spouse or
      dependent children totally independent of their relationship to the filer.
      Additional exceptions apply.
    type: object
    properties:
#      file:
#        type: string
      '#':
        type: string
      source-name:
        type: string
      city-state:
        type: string
      brief-description:
        type: string
      value:
        type: string
  endnotes:
    title: Endnotes
    type: object
    properties:
 #     file:
 #       type: string
      part:
        type: string
      '#':
        type: string
      endnote:
        type: string
